### ISSUE TITLE
Key image already spent in blockchain

### ISSUE THREAD

**Issue by ghost** [CanadianRepublican/monero-universal-pool#3]
Hello, I have lot of errors like:

> [RPC0]	ERROR	verify	src/cryptonote_core/blockchain.cpp:2557	Key image already spent in blockchain: 9f06e5ef533106a570734f7e4cc38256dcfe8d89319bd992ecfe83df32b88b60

What could it be?
Thanks.

**Comment by ZachVan** [comment]
Have you tried deleting your blockchain and re-downloading it? Monerod has a lot of weird issues that re-downloading fixes.
